on:
  schedule:
    - cron: '1 16 * * *'

jobs:
  create_issues_action:
    runs-on: ubuntu-latest
    name: create issues action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create issues action
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
